<?xml version='1.0' encoding='UTF-8'?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hector_world_model</name>
  <version>0.0.0</version>
  <description>TODO</description>

  <maintainer email="marekdaniv@stud.tu-darmstadt.de">md26woxu</maintainer>
  <license>TODO</license>
  <author email="marek.daniv@stud.tu-darmstadt.de">Marek Daniv</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>eigen</depend>
  <depend>hector_perception_msgs</depend>
  <depend>hector_worldmodel_msgs</depend>
  <depend>image_projection_msgs</depend>
  <depend>libopencv-dev</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
